data: "nasbench1shot1.data"
gpu: 0
seed: 2
report_freq: 50

init_channels: 16
layers: 9
model_path: "nashbench1shot1.saved_models"

batch_size: 96
learning_rate: 0.025
learning_rate_min: 0.001
momentum: 0.9
weight_decay: 3e-4
epochs: 50
warm_start_epochs: 0
grad_clip: 5
train_portion: 0.5

cutout: False
cutout_length: 16
cutout_prob: 1.0
drop_path_prob: 0.3

unrolled: False
arch_learning_rate: 3e-4
arch_weight_decay: 1e-3
output_weights: True

